### ISSUE TITLE
ImageDataGenerator 问题

### ISSUE THREAD

**Issue by qilicun** [pengpaiSH/Kaggle_NCFM#1]
Hi, 你好！

我看了之前你在keras上的提问 https://github.com/fchollet/keras/issues/3059
就是datagen怎么同时作用于img和mask的问题。我看你这个代码里面用了，但是用的是flow_from_directory() 我想问问，不如果不用flow_from_directory这个函数而直接用flow()的话怎么设置img和mask的datagen？
非常感谢！

**Comment by pengpaiSH** [comment]
@qilicun Liuming，你好，目前keras的原生环境并不直接支持这个功能，建议你看一下这个libhttps://github.com/aleju/imgaug 我现在数据扩增都是用它。

**Comment by qilicun** [comment]
@pengpaiSH 非常感谢！这个可以直接和keras的fit_generator结合吗？

**Comment by pengpaiSH** [comment]
@qilicun 不好意思晚回复了，可以的！

**Comment by zhengvh** [comment]
@pengpaiSH 您好，想用keras中的flow_from_directory和fit_generator用于语义分割的任务，但是按照官方给出了例子，https://keras-cn.readthedocs.io/en/latest/preprocessing/image/  同时变换图像和mask的例子，发现并不能实现这个功能啊！是Keras不支持img和label同时变换嘛，然后不能够像分类任务一样使用flow_from_directory来训练模型嘛？
